CREATE DATABASE Universidad_Alumnos_info
USE Universidad_Alumnos_info

--TABLAS SIMPLES
CREATE TABLE CARRERA(
NOCARRERA CHAR(3) PRIMARY KEY,
CARRERA VARCHAR(30))

CREATE TABLE MATERIA(
NUMMATERIA CHAR(3) PRIMARY KEY,
MATERIA VARCHAR(30))

CREATE TABLE TIPO_TEL(
ID_TIPOTEL CHAR(3) PRIMARY KEY,
TIPOTEL VARCHAR(20))

CREATE TABLE DELEGACION(
ID_DELEGACION CHAR(5) PRIMARY KEY,
DELEGACION VARCHAR(30))

--TABLAS DEPENDIENTES
CREATE TABLE COLONIA(
ID_COLONIA CHAR(5) PRIMARY KEY,
COLONIA VARCHAR(40),
ID_DELEGACION2 CHAR(5) FOREIGN KEY REFERENCES DELEGACION (ID_DELEGACION))

CREATE TABLE CALLE(
ID_CALLE CHAR(5) PRIMARY KEY,
CALLE VARCHAR(40),
ID_COLONIA2 CHAR(5) FOREIGN KEY REFERENCES COLONIA (ID_COLONIA))

--

CREATE TABLE ALUMNO(
MATRICULA_ALU CHAR(10) PRIMARY KEY,
NOMBRE_ALU VARCHAR(25),
APP_ALU VARCHAR(20),
APM_ALU VARCHAR(20),
ID_DELEGACION1 CHAR(5) FOREIGN KEY REFERENCES DELEGACION (ID_DELEGACION),
ID_COLONIA1 CHAR(5) FOREIGN KEY REFERENCES COLONIA (ID_COLONIA),
ID_CALLE1 CHAR(5) FOREIGN KEY REFERENCES CALLE (ID_CALLE),
NUM_INT VARCHAR(8),
NUM_EXT VARCHAR(8),
CP VARCHAR(5),
NOCARRERA1 CHAR(3) FOREIGN KEY REFERENCES CARRERA (NOCARRERA))

--TABLAS INTERMEDIAS

CREATE TABLE ALUMNO_MATERIA(
MATRICULA_ALU1 CHAR(10) FOREIGN KEY REFERENCES ALUMNO (MATRICULA_ALU),
NUMMATERIA1 CHAR(3) FOREIGN KEY REFERENCES MATERIA (NUMMATERIA))

CREATE TABLE ALUMNO_TIPOTEL(
ID_TIPOTEL1 CHAR(3) FOREIGN KEY REFERENCES TIPO_TEL (ID_TIPOTEL),
MATRICULA_ALU2 CHAR(10) FOREIGN KEY REFERENCES ALUMNO (MATRICULA_ALU),
TELEFONO BIGINT)